# Generated by Django 3.1.5 on 2021-01-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.CharField(default='kategoria', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='nazwa', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product'),
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product'),
        ),
    ]
