# Generated by Django 3.1.5 on 2021-01-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210119_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='kategoria', max_length=30),
            preserve_default=False,
        ),
    ]
